name: Build and Release App (All Platforms) for latest release

on:
  push:
    branches:
      - main
      - master
jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build with PyInstaller
        run: |
          uv run pyinstaller main.py --onefile --windowed --name metadata-cleaner-${{ matrix.os }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          tag: latest
          overwrite: true
          file_glob: true
